ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--CREACION DE USUARIO
CREATE USER C##ADMINISTRADOR
IDENTIFIED BY SEGURIDAD43
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON SYSTEM;
----------------------------------------------------------------|
--PARA ELIMINAR EL USUARIO QUE CREAMOS
DROP USER C##ADMINISTRADOR CASCADE;--CASCADE SE LE COLOCA PARA QUE OMITA CUALQUIER RESTRICCCION SI QUEREMOS ELIMINARLO
--------------------------------------------------------------|
--PARA DARLE PRIVILEGIOS A NUESTRO NUEVO USUARIO
GRANT CREATE SESSION TO C##ADMINISTRADOR;
------------------------------------------------------------|
--PARA QUITARLE LOS PRIVILEGIOS QUE LE DIMOS
--REMOVE CREATE SESSION FROM ADMINISTRADOR;
-------------------------------------------------------------|

--1 DANDOLE PERMISOS PARA CREACION DE TABLAS

GRANT CREATE TABLE TO C##ADMINISTRADOR;

--LISTA DE USUARIOS Y SUS DETALLES
SELECT * FROM DBA_USERS ORDER BY USERNAME;


--MODIFICAR UN USUARIO
ALTER USER C##ADMINISTRADOR
IDENTIFIED BY "ADMIN"
QUOTA 20K ON SYSTEM;

-- CREANDOLE UN ROL A NUESTRO USUARIO
CREATE ROLE C##PRUEBA
NOT IDENTIFIED;

--ELIMINANDO EL ROL CREADO
DROP ROLE C##PRUEBA;

--MOSTRAR LOS ROLES DE LA BD
SELECT * FROM DBA_ROLES ORDER BY ROLE;

--CONSULTAR PRIVILEGIOS DEL SISTEMA ASIGNADOS A USUARIOS Y ROLES
SELECT * FROM DBA_SYS_PRIVS
ORDER BY GRANTEE;

--ASIGNAR UN PRIVILEGIO AL ROL
GRANT CREATE SESSION TO C##PRUEBA; --PARA INICIAR SESION
GRANT CREATE TABLE TO C##PRUEBA; -- PARA CREAR TABLA
GRANT CREATE VIEW TO C##PRUEBA; --PARA CREAR VISTA
GRANT CREATE SEQUENCE TO C##PRUEBA; --PARA CREAR SECUENCIA

--ASIGNAR EL ROL AL USUARIO
GRANT C##PRUEBA TO C##ADMINISTRADOR;

--
SELECT * FROM SYS. --; --colocar la tabla

--PARA DARLE PRIVILEGIOS PARA QUE EL USUARIO QUE QUEREMOS PUEDA CONSULTAR LA TABLA PERTENECIENTE A SYS
GRANT SELECT ON SYS. TO C##ADMINISTRADOR;

--CREAR UN PERFIL PARA EL USUARIO 
CREATE PROFILE C##PERFIL LIMIT
FAILED_LOGIN_ATTEMPTS 3 --ERRORES EN CONTRASEÑA ANTES DE BLOQUEAR LA CUENTA
PASSWORD_LIFE_TIME 60 --DIAS DE VIGENCIA LA CONTRASEÑA
PASSWORD_REUSE_MAX 5 --CAMBIO DE CONTRASEÑA ACTUAL
PASSWORD_GRACE_TIME 15 --DIAS DE PERIODO DE GRACIA PARA LA CONTRASEÑA LUEGO DE SU TIEMPO DE VIDA

--ASIGNAR EL PERFIL CREADO AL USUARIO 
ALTER USER C##ADMINISTRADOR PROFILE C##PERFIL;

--administrador
--uno que solo pueda ver
--roles de gerente, de empleado,


--------------------------------------------------------------------------------------------------------------------
---creacion de usuario encriptado
CREATE TABLE USUARIOS(
    USUARIO VARCHAR2(30 BYTE), 
    CONTRASEÑA VARBINARY (MAX)
   );

ALTER PROC SP_INSERT_USUARIOS
@USERS VARCHAR(MAX),
@PSS VARCHAR(MAX)
AS
DECLARE
@PSSB VARBINARY(MAX)
BEGIN
SET @PSSB=(ENCRYPTBYPASSPHRASE('ENCRIPTACION',@PSS));
INSERT INTO USUARIOS VALUES(@USERS,@PSSB)
ENDCREATE TABLE USUARIOS(
    USUARIO VARCHAR2(MIN), 
    CONTRASEÑA VARBINARY(MAX)
   )SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

ALTER PROC SP_INSERT_USUARIOS
@USERS VARCHAR(MAX),
@PSS VARCHAR(MAX)
AS
DECLARE
@PSSB VARBINARY(MAX)
BEGIN
SET @PSSB=(ENCRYPTBYPASSPHRASE('ENCRIPTACION',@PSS));
INSERT INTO USUARIOS VALUES(@USERS,@PSSB)
END

DROP TABLE USUARIOS
------------------------------------------------------------------------------------------------------------------------

create table usuario(
nombre_usuario varchar2(50),
password_usuario varchar2(10)
);

insert into usuario values ('alfredo',ENCRYPT_DES(SEGURIDAD))
CREATE TABLE USUARIO (
     first_name VARCHAR2(128),
     last_name VARCHAR2(128),
     empID NUMBER,
     salary NUMBER(6) ENCRYPT);

ALTER TABLE usuario MODIFY (password_usuario ENCRYPT);

DROP TABLE USUARIO

select username, password from dba_users;
