------CREACION DE LA TABLA PERSONA------
  CREATE TABLE PERSONA 
   (Id_persona INTEGER,
    NO_DOC_ID NUMBER(30,0),
	NOMBRE1 VARCHAR2(30 BYTE),
    NOMBRE2 VARCHAR2(30 BYTE),
    OTRO_NOMBRE VARCHAR2(30 BYTE),
    APELLIDO1 VARCHAR2(30 BYTE),
    APELLIDO2 VARCHAR2(30 BYTE),
    APELLIDO_CASADA VARCHAR2(30 BYTE),
    TELEFONO NUMBER(8,0),
    FECHA_NACIMIENTO DATE,
    CONSTRAINT PK_PERSONA PRIMARY KEY(ID_PERSONA)   --Se crea la llave primaria de la tabla persona
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---------CREACION DE LA TABLA TIPO_DOC
CREATE TABLE TIPO_DOC
   (ID_TIPO_DOC INTEGER, 
    TIPO_DOC VARCHAR2(30 BYTE),
    CONSTRAINT PK_TIPO_DOC PRIMARY KEY(ID_TIPO_DOC)--DECLARAMOS LA LLAVE PRIMARIA
    --CONSTRAINT FK_TIPODOC FOREIGN KEY(ID_TIPO_DOC) REFERENCES PERSONA(NO_DOC_ID)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA CLIENTE
CREATE TABLE CLIENTE 
   (Id_CLIENTE INTEGER, 
    FECHA_NACIMIENTO DATE,
    Id_ESTADO_CLIENTE INTEGER,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (Id_CLIENTE),--DECLARAMOS LA LLAVE PRIMARIA
    CONSTRAINT FK_CLIENTE_ESTADO FOREIGN KEY (Id_ESTADO_CLIENTE) REFERENCES ESTADO(ID_ESTADO),
    CONSTRAINT FK_CLIENTE_PERSONA FOREIGN KEY(Id_CLIENTE) REFERENCES PERSONA(Id_persona)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
---------------------------------------------------------------------------
--------------------------------------------------------------------------
-------CREACION DE LA TABLA TURNO
CREATE TABLE TURNO 
   (ID_TURNO INTEGER,
    NOMBRE_TURNO VARCHAR2(10 BYTE),
    HORA_INICIO DATE,
    HORA_FINAL DATE,
    CONSTRAINT PK_TURNO PRIMARY KEY (ID_TURNO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA TURNO_EMPLEADO
CREATE TABLE TURNO_EMPLEADO
   (Id_TURNO_EMPLEADO INTEGER, 
    TIPO_TURNO VARCHAR2(10 BYTE),
    FECHA_INICIO_TURNO DATE,
    FECHA_FINAL_TURNO DATE,
    CONSTRAINT PK_TURNO_EMPLEADO PRIMARY KEY (Id_TURNO_EMPLEADO),--DECLARAMOS LA LLAVE PRIMARIA
    CONSTRAINT FK_TUREMPLEADO_TURNO FOREIGN KEY (Id_TURNO_EMPLEADO) REFERENCES TURNO(ID_TURNO)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA ESTADO
CREATE TABLE ESTADO
   (Id_ESTADO INTEGER, 
    DESCRIPCION_ESTADO VARCHAR2(30 BYTE),
    CONSTRAINT PK_ESTADO PRIMARY KEY (Id_ESTADO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
        ---CREACION DE LA TABLA EMPLEADO_PUESTO
CREATE TABLE EMPLEADO_PUESTO
   (ID_EMPLEADO_PUESTO INTEGER,
   FECHA_INICIO_PUESTO DATE,
   FECHA_FINAL_PUESTO DATE,
    CONSTRAINT PK_EMPLEADO_PUESTO PRIMARY KEY(ID_EMPLEADO_PUESTO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA EMPLEADO
CREATE TABLE EMPLEADO
   (Id_EMPLEADO INTEGER,
    FECHA_CONTRATACION DATE,
    ID_ESTADO_EMPLEADO INTEGER,
    ID_PUESTO_TRABAJADOR INTEGER,
    FECHA_BAJA DATE,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (Id_EMPLEADO),--DECLARAMOS LA LLAVE PRIMARIA
    CONSTRAINT FK_EMPLEADO_ESTADO FOREIGN KEY(Id_ESTADO_EMPLEADO) REFERENCES ESTADO(Id_ESTADO),
    CONSTRAINT FK_EMPLEADO_PUESTO FOREIGN KEY(ID_PUESTO_TRABAJADOR) REFERENCES EMPLEADO_PUESTO(Id_EMPLEADO_PUESTO)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------

 ---CREACION DE LA TABLA PUESTO
CREATE TABLE PUESTO
   (ID_PUESTO INTEGER, 
    NOMBRE_PUESTO VARCHAR2(30 BYTE),
    SALARIO NUMBER(6,2),
    CONSTRAINT PK_PUESTO PRIMARY KEY(ID_PUESTO),--DECLARAMOS LA LLAVE PRIMARIA
    CONSTRAINT FK_EMPPUESTO_PUESTO FOREIGN KEY(ID_PUESTO) REFERENCES EMPLEADO_PUESTO(Id_EMPLEADO_PUESTO)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA MOTIVO_BAJA  
CREATE TABLE MOTIVO_BAJA
   (ID_BAJA INTEGER, 
    MOTIVO_BAJA VARCHAR2(150 BYTE),
    CONSTRAINT PK_MOTIVO_BAJA PRIMARY KEY(ID_BAJA)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
  ---CREACION DE LA TABLA PROVEEDOR  
CREATE TABLE PROVEEDOR
   (ID_PROVEEDOR INTEGER,
    DIRECCION VARCHAR2(30 BYTE),
    ID_ESTADO_PRODUCTO INTEGER,
    ID_PUESTO_PROVEEDOR INTEGER,
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY(ID_PROVEEDOR),--DECLARAMOS LA LLAVE PRIMARIA
    CONSTRAINT FK_PRODUCTO_ESTADO FOREIGN KEY(ID_ESTADO_PRODUCTO) REFERENCES ESTADO(Id_ESTADO),
    CONSTRAINT FK_PROVEE_ESTADO FOREIGN KEY(ID_PUESTO_PROVEEDOR) REFERENCES ESTADO(Id_ESTADO)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA SERVICIO_PROVEEDOR  
CREATE TABLE SERVICIO_PROVEEDOR
   (ID_PRODUCTO_PROVEEDOR INTEGER,
    NOMBRE_PRODUCTO VARCHAR2(30 BYTE),
    NOMBRE_SERVICIO VARCHAR2(30 BYTE),
    CONSTRAINT PK_SERVICIO_PROVEEDOR PRIMARY KEY(ID_PRODUCTO_PROVEEDOR),--DECLARAMOS LA LLAVE PRIMARIA
    CONSTRAINT FK_SERPROV_PROVEE FOREIGN KEY(ID_PRODUCTO_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
    CONSTRAINT FK_SERPROV_PRODUC FOREIGN KEY(ID_PRODUCTO_PROVEEDOR) REFERENCES PRODUCTO(ID_PRODUCTO)
    )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
--------------------------------------------------------------------------
--------------------------------------------------------------------------  
---CREACION DE LA TABLA SEDE
CREATE TABLE SEDE
   (ID_SEDE INTEGER, 
    NOMBRE_SEDE VARCHAR2(20 BYTE),
    CONSTRAINT PK_SEDE PRIMARY KEY(ID_SEDE)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA MUNICIPIO
CREATE TABLE MUNICIPIO
   (ID_MUNICIPIO INTEGER, 
    NOMBRE_MUNICIPIO VARCHAR2(20 BYTE),
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY(ID_MUNICIPIO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA DEPARTAMENTO
CREATE TABLE DEPARTAMENTO
   (ID_DEPARTAMENTO INTEGER, 
    NOMBRE_DEPARTAMENTO VARCHAR2(30 BYTE),
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(ID_DEPARTAMENTO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA DETALLE_FACTURA
CREATE TABLE DETALLE_FACTURA
   (ID_DETALLE_FACTURA INTEGER, 
    CANTIDAD NUMBER(10,0),
    PRECIO NUMBER(6,2),
    TOTAL NUMBER(6,2),
    DESCRIPCION VARCHAR2(100 BYTE),
    NIT VARCHAR2(10 BYTE),
    FECHA DATE,
    CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY(ID_DETALLE_FACTURA)--DECLARAMOS LA LLAVE PRIMARIA
    )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA FACTURA
CREATE TABLE FACTURA
   (ID_VENTA INTEGER, 
    FECHA_FACTURA DATE,
    CONSTRAINT PK_FACTURA PRIMARY KEY(ID_VENTA)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA CONTROL_PAGO
CREATE TABLE CONTROL_PAGO
   (ID_CONTROL_PAGO INTEGER,
    MONTO NUMBER(8,2),
    CONSTRAINT CONTROL_PAGO PRIMARY KEY(ID_CONTROL_PAGO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
---CREACION DE LA TABLA PAGO
CREATE TABLE PAGO
   (ID_PAGO INTEGER, 
    FORMA_PAGO VARCHAR2(10 BYTE),
    CONSTRAINT PK_PAGO PRIMARY KEY(ID_PAGO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
  ---CREACION DE LA TABLA TIPO_PRODUCTO
CREATE TABLE TIPO_PRODUCTO
   (ID_TIPO_PRODUCTO INTEGER, 
    TIPO_PRODUCTO VARCHAR2(30 BYTE),
    TIPO_MEDIDA VARCHAR2(30 BYTE),
    CONSTRAINT PK_TIPO_PRODUCTO PRIMARY KEY(ID_TIPO_PRODUCTO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------------------------
--------------------------------------------------------------------------
  ---CREACION DE LA TABLA VEHICULO
CREATE TABLE VEHICULO
   (ID_VEHICULO INTEGER, 
    NUMERO_MATRICULA VARCHAR2(10 BYTE),
    ANIO INTEGER,
    CONSTRAINT PK_VEHICULO PRIMARY KEY(ID_VEHICULO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
  ---CREACION DE LA TABLA TIPO_MATRICULA
CREATE TABLE TIPO_MATRICULA
   (ID_TIPO_MATRICULA INTEGER, 
    NOMBRE_MATRICULA VARCHAR2(10 BYTE),
    TIPO_MATRICULA VARCHAR2(10 BYTE),
    CONSTRAINT PK_TIPO_MATRICULA PRIMARY KEY(ID_TIPO_MATRICULA)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
  ---CREACION DE LA TABLA MATRICULA
CREATE TABLE MARCA
   (ID_MARCA INTEGER, 
    NOMBRE_MARCA VARCHAR2(25 BYTE),
    CONSTRAINT PK_MARCA PRIMARY KEY(ID_MARCA)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------------------------
--------------------------------------------------------------------------
  ---CREACION DE LA TABLA COLOR
CREATE TABLE COLOR
   (ID_COLOR INTEGER, 
    NOMBRE_COLOR VARCHAR2(20 BYTE),
    CONSTRAINT PK_COLOR PRIMARY KEY(ID_COLOR)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
  ---CREACION DE LA TABLA LINEA
CREATE TABLE LINEA
   (ID_LINEA INTEGER, 
    NOMBRE_LINEA VARCHAR2(20 BYTE),
    CONSTRAINT PK_LINEA PRIMARY KEY(ID_LINEA)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
    ---CREACION DE LA TABLA PRODUCTO
CREATE TABLE PRODUCTO
   (ID_PRODUCTO INTEGER, 
    NOMBRE_PRODUCTO VARCHAR2(30 BYTE),
    PRECIO_PRODUCTO DECIMAL(14,2),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO)--DECLARAMOS LA LLAVE PRIMARIA
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------------------------
--------------------------------------------------------------------------

          ---CREACION DE LA TABLA SEDE_PRODUCTO
CREATE TABLE SEDE_PRODUCTO
   (ID_SEDE_PRODUCTO INTEGER,
   CANTIDAD NUMBER(14,2),
    CONSTRAINT PK_SEDE_PRODUCTO PRIMARY KEY(ID_SEDE_PRODUCTO),--DECLARAMOS LA LLAVE PRIMARIA
    CONSTRAINT FK_SEDE_PROD FOREIGN KEY(ID_SEDE_PRODUCTO) REFERENCES PROVEEDOR(ID_PROVEEDOR)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE TABLE CONTROL_PUESTO(
    USUARIO VARCHAR2(30 BYTE), 
	FECHA DATE, 
	OPERACION VARCHAR2(30 BYTE)
   )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
  CREATE TABLE CONTROL_EMPLEADO
   (	USUARIO VARCHAR2(20 BYTE), 
	FECHA DATE, 
	ACCION VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  