------------EJECUTA ESO PRIMERO--------
 
 SET SERVEROUTPUT ON;
  --CREACION DE ESPECIFICACION DE PAQUETE
  CREATE OR REPLACE PACKAGE LOS_PRODUCTOS AS
  PROCEDURE CARACTERISTICAS(V_ID PRODUCTO.ID_PRODUCTO%TYPE);
  END LOS_PRODUCTOS;
  
-------------EJECUTA ESO SEGUNDO-----------------
--CREACION DE BODY DE PAQUETE
  CREATE OR REPLACE PACKAGE BODY LOS_PRODUCTOS AS
  PROCEDURE CARACTERISTICAS(V_ID PRODUCTO.ID_PRODUCTO%TYPE) IS
    V_PRODUCTO PRODUCTO.NOMBRE_PRODUCTO%TYPE;
    V_PRECIO PRODUCTO.PRECIO_PRODUCTO%TYPE;
BEGIN
 SELECT NOMBRE_PRODUCTO, PRECIO_PRODUCTO INTO V_PRODUCTO, V_PRECIO
 FROM PRODUCTO WHERE ID_PRODUCTO = V_ID;
 DBMS_OUTPUT.PUT_LINE('ARTICULO ' || V_PRODUCTO);
 DBMS_OUTPUT.PUT_LINE('PRECIO ' || V_PRECIO);
 END CARACTERISTICAS;
END LOS_PRODUCTOS;

-------------LO SIGUIENTE ES PARA LA PRUEBA EL CODIGO LO PODES MODIFICAR DEPENDIENDO DE LO QUE SE DESEA CONSULTAR--
BEGIN
    LOS_PRODUCTOS.CARACTERISTICAS(2);
    END;


--------ENTRAS AL PAQUETE DE LOS_PRODUCTOS Y MODIFICAS LO QUE TIENE DENTRO LUEGO SE EJECUTA-------
create or replace NONEDITIONABLE PACKAGE LOS_PRODUCTOS AS
  PROCEDURE CARACTERISTICAS(V_ID PRODUCTO.ID_PRODUCTO%TYPE);
  FUNCTION F_PRECIO(V_ID INT)
  RETURN NUMBER;
  END LOS_PRODUCTOS;

-------------MOSTRARA ERROR EN EL SIGUIENTE PAQUETE "BODY" PARA SOLUCIONARLO ENTRA AL PAQUETE QUE TIENE ERROR Y COLOCAS---
create or replace NONEDITIONABLE PACKAGE BODY LOS_PRODUCTOS AS
  PROCEDURE CARACTERISTICAS(V_ID PRODUCTO.ID_PRODUCTO%TYPE) IS
    V_PRODUCTO PRODUCTO.NOMBRE_PRODUCTO%TYPE;
    V_PRECIO PRODUCTO.PRECIO_PRODUCTO%TYPE;
BEGIN
 SELECT NOMBRE_PRODUCTO, PRECIO_PRODUCTO INTO V_PRODUCTO, V_PRECIO
 FROM PRODUCTO WHERE ID_PRODUCTO = V_ID;
 DBMS_OUTPUT.PUT_LINE('ARTICULO ' || V_PRODUCTO);
 DBMS_OUTPUT.PUT_LINE('PRECIO ' || V_PRECIO);
 END CARACTERISTICAS;
 

 -----------------------------------------------------------
 FUNCTION F_PRECIO(V_ID INT)
 RETURN NUMBER
 AS
    V_PRECIO NUMBER;
    BEGIN
    SELECT PRECIO_PRODUCTO INTO V_PRECIO
    FROM PRODUCTO WHERE ID_PRODUCTO = V_ID;
    RETURN V_PRECIO;
END F_PRECIO;
 
 
END LOS_PRODUCTOS;