------CREACION DE LA TABLA PERSONA------
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_PERSONA(
 P_Id_persona IN PERSONA.Id_persona%TYPE,
 P_No_Doc_Id IN  PERSONA.No_Doc_Id%TYPE,
 P_NOMBRE1 IN PERSONA.NOMBRE1%TYPE,
 P_NOMBRE2 IN PERSONA.NOMBRE2%TYPE,
 P_OTRO_NOMBRE IN  PERSONA.OTRO_NOMBRE%TYPE,
 P_APELLIDO1 IN PERSONA.APELLIDO1%TYPE,
 P_APELLIDO2 IN PERSONA.APELLIDO2%TYPE,
 P_APELLIDO_CASADA IN PERSONA.APELLIDO_CASADA%TYPE,
 P_TELEFONO IN  PERSONA.TELEFONO%TYPE,
 P_FECHA_NACIMIENTO IN PERSONA.FECHA_NACIMIENTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO PERSONA VALUES(P_Id_persona, P_No_Doc_Id, P_NOMBRE1, P_NOMBRE2, P_OTRO_NOMBRE, P_APELLIDO1, P_APELLIDO2, P_APELLIDO_CASADA, P_TELEFONO, P_FECHA_NACIMIENTO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
 --------------------------------------------------------------------------
 --------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_PERSONA(
 P_Id_persona IN PERSONA.Id_persona%TYPE,
 P_No_Doc_Id IN  PERSONA.No_Doc_Id%TYPE,
 P_NOMBRE1 IN PERSONA.NOMBRE1%TYPE,
 P_NOMBRE2 IN PERSONA.NOMBRE2%TYPE,
 P_OTRO_NOMBRE IN  PERSONA.OTRO_NOMBRE%TYPE,
 P_APELLIDO1 IN PERSONA.APELLIDO1%TYPE,
 P_APELLIDO2 IN PERSONA.APELLIDO2%TYPE,
 P_APELLIDO_CASADA IN PERSONA.APELLIDO_CASADA%TYPE,
 P_TELEFONO IN  PERSONA.TELEFONO%TYPE,
 P_FECHA_NACIMIENTO IN PERSONA.FECHA_NACIMIENTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE PERSONA
   SET No_Doc_Id=P_No_Doc_Id, NOMBRE1=P_NOMBRE1, NOMBRE2=P_NOMBRE2, OTRO_NOMBRE=P_OTRO_NOMBRE, APELLIDO1=P_APELLIDO1, APELLIDO2=P_APELLIDO2, APELLIDO_CASADA=P_APELLIDO_CASADA, TELEFONO=P_TELEFONO, FECHA_NACIMIENTO=P_FECHA_NACIMIENTO
   WHERE Id_persona= P_Id_persona;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
 --------------------------------------------------------------------------
 --------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_DELETE_PERSONA(
  P_Id_persona IN PERSONA.Id_persona%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM PERSONA
   WHERE Id_persona= P_Id_persona;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;
 
 
---------CREACION DE LA TABLA TIPO_DOC
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_TIPO_DOC(
 P_ID_TIPO_DOC IN TIPO_DOC.ID_TIPO_DOC%TYPE,
 P_TIPO_DOC IN  TIPO_DOC.TIPO_DOC%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO TIPO_DOC VALUES(P_ID_TIPO_DOC, P_TIPO_DOC);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_TIPO_DOC(
 P_ID_TIPO_DOC IN TIPO_DOC.ID_TIPO_DOC%TYPE,
 P_TIPO_DOC IN  TIPO_DOC.TIPO_DOC%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE TIPO_DOC
   SET TIPO_DOC = P_TIPO_DOC
   WHERE ID_TIPO_DOC = P_ID_TIPO_DOC;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_DELETE_TIPO_DOC(
  P_ID_TIPO_DOC IN TIPO_DOC.ID_TIPO_DOC%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM TIPO_DOC
    WHERE ID_TIPO_DOC = P_ID_TIPO_DOC;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;
 
 
---CREACION DE LA TABLA CLIENTE
---------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_CLIENTE(
 P_Id_CLIENTE IN CLIENTE.Id_CLIENTE%TYPE,
 P_FECHA_NACIMIENTO IN  CLIENTE.FECHA_NACIMIENTO%TYPE,
 P_Id_ESTADO_CLIENTE IN CLIENTE.Id_ESTADO_CLIENTE%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO CLIENTE VALUES(P_Id_CLIENTE, P_FECHA_NACIMIENTO, P_Id_ESTADO_CLIENTE);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
-------------------------------------------------------------------------- 
CREATE OR REPLACE PROCEDURE SP_UPDATE_CLIENTE(
 P_Id_CLIENTE IN CLIENTE.Id_CLIENTE%TYPE,
 P_FECHA_NACIMIENTO IN  CLIENTE.FECHA_NACIMIENTO%TYPE,
 P_Id_ESTADO_CLIENTE IN CLIENTE.Id_ESTADO_CLIENTE%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE CLIENTE
   SET FECHA_NACIMIENTO = P_FECHA_NACIMIENTO, Id_ESTADO_CLIENTE=P_Id_ESTADO_CLIENTE
   WHERE Id_CLIENTE= P_Id_CLIENTE;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
-------------------------------------------------------------------------- 
CREATE OR REPLACE PROCEDURE SP_DELETE_CLIENTE(
  P_Id_CLIENTE IN CLIENTE.Id_CLIENTE%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM CLIENTE
   WHERE Id_CLIENTE= P_Id_CLIENTE;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


-------CREACION DE LA TABLA TURNO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_TURNO(
 P_ID_TURNO IN TURNO.ID_TURNO%TYPE,
 P_NOMBRE_TURNO IN TURNO.NOMBRE_TURNO%TYPE,
 P_HORA_INICIO IN  TURNO.HORA_INICIO%TYPE,
 P_HORA_FINAL IN  TURNO.HORA_FINAL%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO TURNO VALUES(P_ID_TURNO, P_NOMBRE_TURNO,P_HORA_INICIO,P_HORA_FINAL );
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_TURNO(
 P_ID_TURNO IN TURNO.ID_TURNO%TYPE,
 P_NOMBRE_TURNO IN TURNO.NOMBRE_TURNO%TYPE,
 P_HORA_INICIO IN  TURNO.HORA_INICIO%TYPE,
 P_HORA_FINAL IN  TURNO.HORA_FINAL%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE TURNO
   SET NOMBRE_TURNO = P_NOMBRE_TURNO , HORA_INICIO = P_HORA_INICIO, HORA_FINAL =P_HORA_FINAL
   WHERE ID_TURNO = P_ID_TURNO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_DELETE_TURNO(
  P_ID_TURNO IN TURNO.ID_TURNO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM TURNO
    WHERE Id_TURNO = P_Id_TURNO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

---CREACION DE LA TABLA TURNO_EMPLEADO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_TURNO_EMPLEADO(
 P_Id_TURNO_EMPLEADO IN TURNO_EMPLEADO.Id_TURNO_EMPLEADO%TYPE,
 P_TIPO_TURNO IN  TURNO_EMPLEADO.TIPO_TURNO%TYPE,
 P_FECHA_INICIO_TURNO IN  TURNO_EMPLEADO.FECHA_INICIO_TURNO%TYPE,
 P_FECHA_FINAL_TURNO IN  TURNO_EMPLEADO.FECHA_FINAL_TURNO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO TURNO_EMPLEADO VALUES(P_Id_TURNO_EMPLEADO, P_TIPO_TURNO, P_FECHA_INICIO_TURNO, P_FECHA_FINAL_TURNO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_TURNO_EMPLEADO(
 P_Id_TURNO_EMPLEADO IN TURNO_EMPLEADO.Id_TURNO_EMPLEADO%TYPE,
 P_TIPO_TURNO IN  TURNO_EMPLEADO.TIPO_TURNO%TYPE,
 P_FECHA_INICIO_TURNO IN  TURNO_EMPLEADO.FECHA_INICIO_TURNO%TYPE,
 P_FECHA_FINAL_TURNO IN  TURNO_EMPLEADO.FECHA_FINAL_TURNO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE TURNO_EMPLEADO
   SET TIPO_TURNO = P_TIPO_TURNO, FECHA_INICIO_TURNO = P_FECHA_INICIO_TURNO, FECHA_FINAL_TURNO = P_FECHA_FINAL_TURNO
   WHERE Id_TURNO_EMPLEADO = P_Id_TURNO_EMPLEADO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_TURNO_EMPLEADO(
  P_Id_TURNO_EMPLEADO IN TURNO_EMPLEADO.Id_TURNO_EMPLEADO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM TURNO_EMPLEADO
    WHERE Id_TURNO_EMPLEADO = P_Id_TURNO_EMPLEADO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
---CREACION DE LA TABLA ESTADO  
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_ESTADO(
 P_Id_ESTADO IN ESTADO.Id_ESTADO%TYPE,
 P_DESCRIPCION_ESTADO IN  ESTADO.DESCRIPCION_ESTADO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO ESTADO VALUES(P_Id_ESTADO, P_DESCRIPCION_ESTADO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_ESTADO(
 P_Id_ESTADO IN ESTADO.Id_ESTADO%TYPE,
 P_DESCRIPCION_ESTADO IN  ESTADO.DESCRIPCION_ESTADO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE ESTADO
   SET DESCRIPCION_ESTADO = P_DESCRIPCION_ESTADO
   WHERE Id_ESTADO = P_Id_ESTADO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_DELETE_ESTADO(
  P_Id_ESTADO IN ESTADO.Id_ESTADO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM ESTADO
    WHERE Id_ESTADO = P_Id_ESTADO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
---CREACION DE LA TABLA EMPLEADO  
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_EMPLEADO(
 P_Id_EMPLEADO IN EMPLEADO.Id_EMPLEADO%TYPE,
 P_FECHA_CONTRATACION IN  EMPLEADO.FECHA_CONTRATACION%TYPE,
 P_ID_ESTADO_EMPLEADO IN EMPLEADO.ID_ESTADO_EMPLEADO%TYPE,
 P_ID_PUESTO_TRABAJADOR IN EMPLEADO.ID_PUESTO_TRABAJADOR%TYPE,
 P_FECHA_BAJA IN EMPLEADO.FECHA_BAJA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO EMPLEADO VALUES(P_Id_EMPLEADO, P_FECHA_CONTRATACION, P_ID_ESTADO_EMPLEADO, P_ID_PUESTO_TRABAJADOR, P_FECHA_BAJA);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_EMPLEADO(
 P_Id_EMPLEADO IN EMPLEADO.Id_EMPLEADO%TYPE,
 P_FECHA_CONTRATACION IN  EMPLEADO.FECHA_CONTRATACION%TYPE,
 P_ID_ESTADO_EMPLEADO IN EMPLEADO.ID_ESTADO_EMPLEADO%TYPE,
 P_ID_PUESTO_TRABAJADOR IN EMPLEADO.ID_PUESTO_TRABAJADOR%TYPE,
 P_FECHA_BAJA IN EMPLEADO.FECHA_BAJA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE EMPLEADO
   SET FECHA_CONTRATACION = P_FECHA_CONTRATACION, ID_ESTADO_EMPLEADO = P_ID_ESTADO_EMPLEADO, ID_PUESTO_TRABAJADOR = P_ID_PUESTO_TRABAJADOR, FECHA_BAJA = P_FECHA_BAJA
   WHERE Id_EMPLEADO= P_Id_EMPLEADO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_EMPLEADO(
  P_Id_EMPLEADO IN EMPLEADO.Id_EMPLEADO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM EMPLEADO
   WHERE Id_EMPLEADO = P_Id_EMPLEADO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


 ---CREACION DE LA TABLA PUESTO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_PUESTO(
 P_ID_PUESTO IN PUESTO.ID_PUESTO%TYPE,
 P_NOMBRE_PUESTO IN  PUESTO.NOMBRE_PUESTO%TYPE,
 P_SALARIO IN PUESTO.SALARIO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO PUESTO VALUES(P_ID_PUESTO, P_NOMBRE_PUESTO, P_SALARIO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_PUESTO(
 P_ID_PUESTO IN PUESTO.ID_PUESTO%TYPE,
 P_NOMBRE_PUESTO IN  PUESTO.NOMBRE_PUESTO%TYPE,
 P_SALARIO IN PUESTO.SALARIO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE PUESTO
   SET NOMBRE_PUESTO = P_NOMBRE_PUESTO, SALARIO=P_SALARIO
   WHERE ID_PUESTO = P_ID_PUESTO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_PUESTO(
  P_ID_PUESTO IN PUESTO.ID_PUESTO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM PUESTO
   WHERE ID_PUESTO = P_ID_PUESTO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


---CREACION DE LA TABLA MOTIVO_BAJA  
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_MOTIVO_BAJA(
 P_ID_BAJA IN MOTIVO_BAJA.ID_BAJA%TYPE,
 P_MOTIVO_BAJA IN  MOTIVO_BAJA.MOTIVO_BAJA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO MOTIVO_BAJA VALUES(P_ID_BAJA, P_MOTIVO_BAJA);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_MOTIVO_BAJA(
 P_ID_BAJA IN MOTIVO_BAJA.ID_BAJA%TYPE,
 P_MOTIVO_BAJA IN  MOTIVO_BAJA.MOTIVO_BAJA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE MOTIVO_BAJA
   SET MOTIVO_BAJA = P_MOTIVO_BAJA
   WHERE ID_BAJA = P_ID_BAJA;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_MOTIVO_BAJA(
  P_ID_BAJA IN MOTIVO_BAJA.ID_BAJA%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM MOTIVO_BAJA
    WHERE ID_BAJA = P_ID_BAJA;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


  ---CREACION DE LA TABLA PROVEEDOR  
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_PROVEEDOR(
 P_ID_PROVEEDOR IN PROVEEDOR.ID_PROVEEDOR%TYPE,
 P_DIRECCION IN  PROVEEDOR.DIRECCION%TYPE,
 P_ID_ESTADO_PRODUCTO IN PROVEEDOR.ID_ESTADO_PRODUCTO%TYPE,
 P_ID_PUESTO_PROVEEDOR IN PROVEEDOR.ID_PUESTO_PROVEEDOR%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO PROVEEDOR VALUES(P_ID_PROVEEDOR, P_DIRECCION, P_ID_ESTADO_PRODUCTO, P_ID_PUESTO_PROVEEDOR);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
-------------------------------------------------------------------------- 
CREATE OR REPLACE PROCEDURE SP_UPDATE_PROVEEDOR(
 P_ID_PROVEEDOR IN PROVEEDOR.ID_PROVEEDOR%TYPE,
 P_DIRECCION IN  PROVEEDOR.DIRECCION%TYPE,
 P_ID_ESTADO_PRODUCTO IN PROVEEDOR.ID_ESTADO_PRODUCTO%TYPE,
 P_ID_PUESTO_PROVEEDOR IN PROVEEDOR.ID_PUESTO_PROVEEDOR%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE PROVEEDOR
   SET DIRECCION = P_DIRECCION, ID_ESTADO_PRODUCTO = P_ID_ESTADO_PRODUCTO ,ID_PUESTO_PROVEEDOR = P_ID_PUESTO_PROVEEDOR
   WHERE ID_PROVEEDOR = P_ID_PROVEEDOR;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_PROVEEDOR(
  P_ID_PROVEEDOR IN PROVEEDOR.ID_PROVEEDOR%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM PROVEEDOR
   WHERE ID_PROVEEDOR = P_ID_PROVEEDOR;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


---CREACION DE LA TABLA SERVICIO_PROVEEDOR  
--------------------------------------------------------------------------
--------------------------------------------------------------------------  
CREATE OR REPLACE PROCEDURE SP_INSERT_SERVICIO_PROVEEDOR(
 P_ID_PRODUCTO_PROVEEDOR IN SERVICIO_PROVEEDOR.ID_PRODUCTO_PROVEEDOR%TYPE,
 P_NOMBRE_PRODUCTO IN  SERVICIO_PROVEEDOR.NOMBRE_PRODUCTO%TYPE,
 P_NOMBRE_SERVICIO IN  SERVICIO_PROVEEDOR.NOMBRE_SERVICIO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO SERVICIO_PROVEEDOR VALUES(P_ID_PRODUCTO_PROVEEDOR, P_NOMBRE_PRODUCTO, P_NOMBRE_SERVICIO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_SERVICIO_PROVEEDOR(
 P_ID_PRODUCTO_PROVEEDOR IN SERVICIO_PROVEEDOR.ID_PRODUCTO_PROVEEDOR%TYPE,
 P_NOMBRE_PRODUCTO IN  SERVICIO_PROVEEDOR.NOMBRE_PRODUCTO%TYPE,
 P_NOMBRE_SERVICIO IN  SERVICIO_PROVEEDOR.NOMBRE_SERVICIO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE SERVICIO_PROVEEDOR
   SET NOMBRE_PRODUCTO = P_NOMBRE_PRODUCTO, NOMBRE_SERVICIO = P_NOMBRE_SERVICIO
   WHERE ID_PRODUCTO_PROVEEDOR = P_ID_PRODUCTO_PROVEEDOR;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_SERVICIO_PROVEEDOR(
  P_ID_PRODUCTO_PROVEEDOR IN SERVICIO_PROVEEDOR.ID_PRODUCTO_PROVEEDOR%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM SERVICIO_PROVEEDOR
    WHERE ID_PRODUCTO_PROVEEDOR = P_ID_PRODUCTO_PROVEEDOR;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


---CREACION DE LA TABLA SEDE
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_SEDE(
 P_ID_SEDE IN SEDE.ID_SEDE%TYPE,
 P_NOMBRE_SEDE IN  SEDE.NOMBRE_SEDE%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO SEDE VALUES(P_ID_SEDE, P_NOMBRE_SEDE);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_SEDE(
 P_ID_SEDE IN SEDE.ID_SEDE%TYPE,
 P_NOMBRE_SEDE IN  SEDE.NOMBRE_SEDE%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE SEDE
   SET NOMBRE_SEDE = P_NOMBRE_SEDE
   WHERE ID_SEDE = P_ID_SEDE;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_SEDE(
  P_ID_SEDE IN SEDE.ID_SEDE%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM SEDE
    WHERE ID_SEDE = P_ID_SEDE;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


---CREACION DE LA TABLA MUNICIPIO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_MUNICIPIO(
 P_ID_MUNICIPIO IN MUNICIPIO.ID_MUNICIPIO%TYPE,
 P_NOMBRE_MUNICIPIO IN  MUNICIPIO.NOMBRE_MUNICIPIO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO MUNICIPIO VALUES(P_ID_MUNICIPIO, P_NOMBRE_MUNICIPIO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_MUNICIPIO(
 P_ID_MUNICIPIO IN MUNICIPIO.ID_MUNICIPIO%TYPE,
 P_NOMBRE_MUNICIPIO IN  MUNICIPIO.NOMBRE_MUNICIPIO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE MUNICIPIO
   SET NOMBRE_MUNICIPIO = P_NOMBRE_MUNICIPIO
   WHERE ID_MUNICIPIO = P_ID_MUNICIPIO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_MUNICIPIO(
  P_ID_MUNICIPIO IN MUNICIPIO.ID_MUNICIPIO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM MUNICIPIO
    WHERE ID_MUNICIPIO = P_ID_MUNICIPIO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


---CREACION DE LA TABLA DEPARTAMENTO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_DEPARTAMENTO(
 P_ID_DEPARTAMENTO IN DEPARTAMENTO.ID_DEPARTAMENTO%TYPE,
 P_NOMBRE_DEPARTAMENTO IN  DEPARTAMENTO.NOMBRE_DEPARTAMENTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO DEPARTAMENTO VALUES(P_ID_DEPARTAMENTO, P_NOMBRE_DEPARTAMENTO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_DEPARTAMENTO(
 P_ID_DEPARTAMENTO IN DEPARTAMENTO.ID_DEPARTAMENTO%TYPE,
 P_NOMBRE_DEPARTAMENTO IN  DEPARTAMENTO.NOMBRE_DEPARTAMENTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE DEPARTAMENTO
   SET NOMBRE_DEPARTAMENTO = P_NOMBRE_DEPARTAMENTO
   WHERE ID_DEPARTAMENTO = P_ID_DEPARTAMENTO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_DEPARTAMENTO(
  P_ID_DEPARTAMENTO IN DEPARTAMENTO.ID_DEPARTAMENTO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM DEPARTAMENTO
    WHERE ID_DEPARTAMENTO = P_ID_DEPARTAMENTO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


---CREACION DE LA TABLA DETALLE_FACTURA
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_DETALLE_FACTURA(
 P_ID_DETALLE_FACTURA IN DETALLE_FACTURA.ID_DETALLE_FACTURA%TYPE,
 P_CANTIDAD IN  DETALLE_FACTURA.CANTIDAD%TYPE,
 P_PRECIO IN DETALLE_FACTURA.PRECIO%TYPE,
 P_TOTAL IN DETALLE_FACTURA.TOTAL%TYPE,
 P_DESCRIPCION IN  DETALLE_FACTURA.DESCRIPCION%TYPE,
 P_NIT IN DETALLE_FACTURA.NIT%TYPE,
 P_FECHA IN DETALLE_FACTURA.FECHA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO DETALLE_FACTURA VALUES(P_ID_DETALLE_FACTURA, P_CANTIDAD, P_PRECIO, P_TOTAL, P_DESCRIPCION, P_NIT, P_FECHA);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_DETALLE_FACTURA(
 P_ID_DETALLE_FACTURA IN DETALLE_FACTURA.ID_DETALLE_FACTURA%TYPE,
 P_CANTIDAD IN  DETALLE_FACTURA.CANTIDAD%TYPE,
 P_PRECIO IN DETALLE_FACTURA.PRECIO%TYPE,
 P_TOTAL IN DETALLE_FACTURA.TOTAL%TYPE,
 P_DESCRIPCION IN  DETALLE_FACTURA.DESCRIPCION%TYPE,
 P_NIT IN DETALLE_FACTURA.NIT%TYPE,
 P_FECHA IN DETALLE_FACTURA.FECHA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE DETALLE_FACTURA
   SET CANTIDAD = P_CANTIDAD, PRECIO = P_PRECIO, TOTAL = P_TOTAL, DESCRIPCION = P_DESCRIPCION, NIT = P_NIT, FECHA = P_FECHA
   WHERE ID_DETALLE_FACTURA = P_ID_DETALLE_FACTURA;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
  CREATE OR REPLACE PROCEDURE SP_DELETE_DETALLE_FACTURA(
  P_ID_DETALLE_FACTURA IN DETALLE_FACTURA.ID_DETALLE_FACTURA%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM DETALLE_FACTURA
   WHERE ID_DETALLE_FACTURA = P_ID_DETALLE_FACTURA;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;


---CREACION DE LA TABLA FACTURA
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_FACTURA(
 P_ID_VENTA IN FACTURA.ID_VENTA%TYPE,
 P_FECHA_FACTURA IN  FACTURA.FECHA_FACTURA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO FACTURA VALUES(P_ID_VENTA, P_FECHA_FACTURA);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_FACTURA(
 P_ID_VENTA IN FACTURA.ID_VENTA%TYPE,
 P_FECHA_FACTURA IN  FACTURA.FECHA_FACTURA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE FACTURA
   SET FECHA_FACTURA = P_FECHA_FACTURA
   WHERE ID_VENTA = P_ID_VENTA;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_FACTURA(
  P_ID_VENTA IN FACTURA.ID_VENTA%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM FACTURA
    WHERE ID_VENTA = P_ID_VENTA;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
---CREACION DE LA TABLA CONTROL_PAGO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_CONTROL_PAGO(
 P_ID_CONTROL_PAGO IN CONTROL_PAGO.ID_CONTROL_PAGO%TYPE,
 P_MONTO IN  CONTROL_PAGO.MONTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO CONTROL_PAGO VALUES(P_ID_CONTROL_PAGO, P_MONTO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_CONTROL_PAGO(
 P_ID_CONTROL_PAGO IN CONTROL_PAGO.ID_CONTROL_PAGO%TYPE,
 P_MONTO IN  CONTROL_PAGO.MONTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE CONTROL_PAGO
   SET MONTO = P_MONTO
   WHERE ID_CONTROL_PAGO = P_ID_CONTROL_PAGO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_CONTROL_PAGO(
  P_ID_CONTROL_PAGO IN CONTROL_PAGO.ID_CONTROL_PAGO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM CONTROL_PAGO
    WHERE ID_CONTROL_PAGO = P_ID_CONTROL_PAGO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
---CREACION DE LA TABLA PAGO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_PAGO(
 P_ID_PAGO IN PAGO.ID_PAGO%TYPE,
 P_FORMA_PAGO IN  PAGO.FORMA_PAGO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO PAGO VALUES(P_ID_PAGO, P_FORMA_PAGO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_PAGO(
 P_ID_PAGO IN PAGO.ID_PAGO%TYPE,
 P_FORMA_PAGO IN  PAGO.FORMA_PAGO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE PAGO
   SET FORMA_PAGO = P_FORMA_PAGO
   WHERE ID_PAGO = P_ID_PAGO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_PAGO(
  P_ID_PAGO IN PAGO.ID_PAGO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM PAGO
    WHERE ID_PAGO = P_ID_PAGO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
  ---CREACION DE LA TABLA TIPO_PRODUCTO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_TIPO_PRODUCTO(
 P_ID_TIPO_PRODUCTO IN TIPO_PRODUCTO.ID_TIPO_PRODUCTO%TYPE,
 P_TIPO_PRODUCTO IN  TIPO_PRODUCTO.TIPO_PRODUCTO%TYPE,
 P_TIPO_MEDIDA IN TIPO_PRODUCTO.TIPO_MEDIDA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO TIPO_PRODUCTO VALUES(P_ID_TIPO_PRODUCTO, P_TIPO_PRODUCTO, P_TIPO_MEDIDA);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_TIPO_PRODUCTO(
 P_ID_TIPO_PRODUCTO IN TIPO_PRODUCTO.ID_TIPO_PRODUCTO%TYPE,
 P_TIPO_PRODUCTO IN  TIPO_PRODUCTO.TIPO_PRODUCTO%TYPE,
 P_TIPO_MEDIDA IN TIPO_PRODUCTO.TIPO_MEDIDA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE TIPO_PRODUCTO
   SET TIPO_PRODUCTO = P_TIPO_PRODUCTO, TIPO_MEDIDA = P_TIPO_MEDIDA
   WHERE ID_TIPO_PRODUCTO = P_ID_TIPO_PRODUCTO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_TIPO_PRODUCTO(
  P_ID_TIPO_PRODUCTO IN TIPO_PRODUCTO.ID_TIPO_PRODUCTO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM TIPO_PRODUCTO
   WHERE ID_TIPO_PRODUCTO = P_ID_TIPO_PRODUCTO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
  ---CREACION DE LA TABLA VEHICULO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_VEHICULO(
 P_ID_VEHICULO IN VEHICULO.ID_VEHICULO%TYPE,
 P_NUMERO_MATRICULA IN  VEHICULO.NUMERO_MATRICULA%TYPE,
 P_ANIO IN VEHICULO.ANIO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO VEHICULO VALUES(P_ID_VEHICULO, P_NUMERO_MATRICULA, P_ANIO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_VEHICULO(
 P_ID_VEHICULO IN VEHICULO.ID_VEHICULO%TYPE,
 P_NUMERO_MATRICULA IN  VEHICULO.NUMERO_MATRICULA%TYPE,
 P_ANIO IN VEHICULO.ANIO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE VEHICULO
   SET NUMERO_MATRICULA = P_NUMERO_MATRICULA, ANIO = P_ANIO
   WHERE ID_VEHICULO = P_ID_VEHICULO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_VEHICULO(
  P_ID_VEHICULO IN VEHICULO.ID_VEHICULO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM VEHICULO
   WHERE ID_VEHICULO = P_ID_VEHICULO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
  ---CREACION DE LA TABLA TIPO_MATRICULA
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_TIPO_MATRICULA(
 P_ID_TIPO_MATRICULA IN TIPO_MATRICULA.ID_TIPO_MATRICULA%TYPE,
 P_NOMBRE_MATRICULA IN  TIPO_MATRICULA.NOMBRE_MATRICULA%TYPE,
 P_TIPO_MATRICULA IN TIPO_MATRICULA.TIPO_MATRICULA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO TIPO_MATRICULA VALUES(P_ID_TIPO_MATRICULA, P_NOMBRE_MATRICULA, P_TIPO_MATRICULA);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_TIPO_MATRICULA(
 P_ID_TIPO_MATRICULA IN TIPO_MATRICULA.ID_TIPO_MATRICULA%TYPE,
 P_NOMBRE_MATRICULA IN  TIPO_MATRICULA.NOMBRE_MATRICULA%TYPE,
 P_TIPO_MATRICULA IN TIPO_MATRICULA.TIPO_MATRICULA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE TIPO_MATRICULA
   SET NOMBRE_MATRICULA = P_NOMBRE_MATRICULA, TIPO_MATRICULA = P_TIPO_MATRICULA
   WHERE ID_TIPO_MATRICULA = P_ID_TIPO_MATRICULA;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_TIPO_MATRICULA(
  P_ID_TIPO_MATRICULA IN TIPO_MATRICULA.ID_TIPO_MATRICULA%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM TIPO_MATRICULA
   WHERE ID_TIPO_MATRICULA = P_ID_TIPO_MATRICULA;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
  ---CREACION DE LA TABLA MATRICULA
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_MARCA(
 P_ID_MARCA IN MARCA.ID_MARCA%TYPE,
 P_NOMBRE_MARCA IN  MARCA.NOMBRE_MARCA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO MARCA VALUES(P_ID_MARCA, P_NOMBRE_MARCA);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_MARCA(
 P_ID_MARCA IN MARCA.ID_MARCA%TYPE,
 P_NOMBRE_MARCA IN  MARCA.NOMBRE_MARCA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE MARCA
   SET NOMBRE_MARCA = P_NOMBRE_MARCA
   WHERE ID_MARCA = P_ID_MARCA;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_MARCA(
  P_ID_MARCA IN MARCA.ID_MARCA%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM MARCA
    WHERE ID_MARCA = P_ID_MARCA;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
  ---CREACION DE LA TABLA COLOR
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_COLOR(
 P_ID_COLOR IN COLOR.ID_COLOR%TYPE,
 P_NOMBRE_COLOR IN  COLOR.NOMBRE_COLOR%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO COLOR VALUES(P_ID_COLOR, P_NOMBRE_COLOR);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_COLOR(
 P_ID_COLOR IN COLOR.ID_COLOR%TYPE,
 P_NOMBRE_COLOR IN  COLOR.NOMBRE_COLOR%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE COLOR
   SET NOMBRE_COLOR = P_NOMBRE_COLOR
   WHERE ID_COLOR = P_ID_COLOR;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_COLOR(
  P_ID_COLOR IN COLOR.ID_COLOR%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM COLOR
    WHERE ID_COLOR = P_ID_COLOR;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
  ---CREACION DE LA TABLA LINEA
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_LINEA(
 P_ID_LINEA IN LINEA.ID_LINEA%TYPE,
 P_NOMBRE_LINEA IN  LINEA.NOMBRE_LINEA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO LINEA VALUES(P_ID_LINEA, P_NOMBRE_LINEA);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_LINEA(
 P_ID_LINEA IN LINEA.ID_LINEA%TYPE,
 P_NOMBRE_LINEA IN  LINEA.NOMBRE_LINEA%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE LINEA
   SET NOMBRE_LINEA = P_NOMBRE_LINEA
   WHERE ID_LINEA = P_ID_LINEA;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END; 
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_LINEA(
  ID_LINEA IN LINEA.ID_LINEA%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM LINEA
    WHERE ID_LINEA = P_ID_LINEA;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
    ---CREACION DE LA TABLA PRODUCTO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_PRODUCTO(
 P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
 P_NOMBRE_PRODUCTO IN  PRODUCTO.NOMBRE_PRODUCTO%TYPE,
 P_PRECIO_PRODUCTO IN PRODUCTO.PRECIO_PRODUCTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO PRODUCTO VALUES(P_ID_PRODUCTO, P_NOMBRE_PRODUCTO, P_PRECIO_PRODUCTO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_UPDATE_PRODUCTO(
 P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
 P_NOMBRE_PRODUCTO IN  PRODUCTO.NOMBRE_PRODUCTO%TYPE,
 P_PRECIO_PRODUCTO IN PRODUCTO.PRECIO_PRODUCTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE PRODUCTO
   SET NOMBRE_PRODUCTO = P_NOMBRE_PRODUCTO, PRECIO_PRODUCTO = P_PRECIO_PRODUCTO
   WHERE ID_PRODUCTO = P_ID_PRODUCTO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_PRODUCTO(
  P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM PRODUCTO
   WHERE ID_PRODUCTO = P_ID_PRODUCTO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
        ---CREACION DE LA TABLA EMPLEADO_PUESTO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERT_EMPLEADO_PUESTO(
 P_ID_EMPLEADO_PUESTO IN EMPLEADO_PUESTO.ID_EMPLEADO_PUESTO%TYPE,
 P_FECHA_INICIO_PUESTO IN  EMPLEADO_PUESTO.FECHA_INICIO_PUESTO%TYPE,
 P_FECHA_FINAL_PUESTO IN EMPLEADO_PUESTO.FECHA_FINAL_PUESTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO EMPLEADO_PUESTO VALUES(P_ID_EMPLEADO_PUESTO, P_FECHA_INICIO_PUESTO, P_FECHA_FINAL_PUESTO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_EMPLEADO_PUESTO(
 P_ID_EMPLEADO_PUESTO IN EMPLEADO_PUESTO.ID_EMPLEADO_PUESTO%TYPE,
 P_FECHA_INICIO_PUESTO IN  EMPLEADO_PUESTO.FECHA_INICIO_PUESTO%TYPE,
 P_FECHA_FINAL_PUESTO IN EMPLEADO_PUESTO.FECHA_FINAL_PUESTO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE EMPLEADO_PUESTO
   SET FECHA_INICIO_PUESTO = P_FECHA_INICIO_PUESTO, FECHA_FINAL_PUESTO = P_FECHA_FINAL_PUESTO
   WHERE ID_EMPLEADO_PUESTO = P_ID_EMPLEADO_PUESTO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_EMPLEADO_PUESTO(
  P_ID_EMPLEADO_PUESTO IN EMPLEADO_PUESTO.ID_EMPLEADO_PUESTO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM EMPLEADO_PUESTO
   WHERE ID_EMPLEADO_PUESTO = P_ID_EMPLEADO_PUESTO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;

  
          ---CREACION DE LA TABLA SEDE_PRODUCTO
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_INSERT_SEDE_PRODUCTO(
 P_ID_SEDE_PRODUCTO IN SEDE_PRODUCTO.ID_SEDE_PRODUCTO%TYPE,
 P_CANTIDAD IN  SEDE_PRODUCTO.CANTIDAD%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO SEDE_PRODUCTO VALUES(P_ID_SEDE_PRODUCTO, P_CANTIDAD);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_UPDATE_SEDE_PRODUCTO(
 P_ID_SEDE_PRODUCTO IN SEDE_PRODUCTO.ID_SEDE_PRODUCTO%TYPE,
 P_CANTIDAD IN  SEDE_PRODUCTO.CANTIDAD%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE SEDE_PRODUCTO
   SET CANTIDAD = P_CANTIDAD
   WHERE ID_SEDE_PRODUCTO = P_ID_SEDE_PRODUCTO;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 CREATE OR REPLACE PROCEDURE SP_DELETE_SEDE_PRODUCTO(
  P_ID_SEDE_PRODUCTO IN SEDE_PRODUCTO.ID_SEDE_PRODUCTO%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM SEDE_PRODUCTO
    WHERE ID_SEDE_PRODUCTO = P_ID_SEDE_PRODUCTO;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;