--CREAMOS UNA VISTA CLIENTE
CREATE VIEW VISTACLIENTE
AS SELECT PER.NOMBRE1, PER.NOMBRE2, PER.APELLIDO1, CL.FECHA_NACIMIENTO
FROM CLIENTE CL, PERSONA PER
WHERE CL.Id_CLIENTE = PER.Id_persona


--MOSTRAMOS LA VISTA CREADA
SELECT * FROM VISTACLIENTE
--BORRAR UNA VISTA
DROP VIEW VISTACLIENTE


--CREAMOS UNA VISTA CLIENTE
CREATE VIEW VISTAEMPLEADO
AS SELECT EM.Id_EMPLEADO, EM.FECHA_CONTRATACION, ST.DESCRIPCION_ESTADO
FROM EMPLEADO EM, ESTADO ST
WHERE EM.Id_ESTADO_EMPLEADO = ST.Id_ESTADO


--MOSTRAMOS LA VISTA CREADA
SELECT * FROM VISTAEMPLEADO
--BORRAR UNA VISTA
DROP VIEW VISTAEMPLEADO